# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00c73f1d87c0d77bad17054795c8680eca7b352ec73e7c6942a070ca37d4f71488b8ea8e3e9c8dc845d86084722445b90d9c015de9001d8010f53b4f5e5d7456

test:
  secret_key_base: a26eda18014b8ec9afb2cbbb0a17ca60dea7c913f6f5c56060f2f31388c3c66ca19e3021587d8bfd5684d4c07bfc6b0e8fd244fa0b5a649b7427a7c4b55c38c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
